# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update git revision 
        run: |
          REVISION=`git log -n 1 --pretty=format:"%H"`
          sed -i -e "s/<% GIT_REVISION %>/$REVISION/g" .env.production
          sed -i -e "s/<% GIT_REVISION %>/$REVISION/g" public/manifest.json

      - name: Update git revision 
        run: yarn install

  deploy-staging:
    runs-on: 'ubuntu-latest'
    environment: 'staging'
    needs: build
    steps:
      - name: Build application
        run: yarn run build-staging

      - name: Upload to S3
        run: echo TODO Upload to S3

  deploy-prod:
    runs-on: 'ubuntu-latest'
    environment: 'production'
    needs: [build, deploy-staging]
    steps:
      - name: Build application
        run: yarn run build

      - name: Upload to S3
        run: echo TODO Upload to S3
        
      - name: Push git tag
        run: echo TODO push git tag
