# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  deploy-prod:
    runs-on: 'ubuntu-latest'
    environment: 'production'
    steps:
      - uses: actions/checkout@v2

      - name: Run deploy script
        run: ./deploy.sh
