# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  deploy-prod:
    runs-on: 'ubuntu-latest'
    environment: 'production'
    steps:
      - uses: actions/checkout@v2

      - name: Update git revision 
        run: |
          REVISION=`git log -n 1 --pretty=format:"%H"`
          sed -i -e "s/<% GIT_REVISION %>/$REVISION/g" .env.production
          sed -i -e "s/<% GIT_REVISION %>/$REVISION/g" public/manifest.json

      - name: Update git revision 
        run: yarn install

      - name: Build application
        run: yarn run build

      - name: Upload to S3
        run: echo TODO Upload to S3
        
      - name: Push git tag
        run: |
          timestamp=`date +%Y-%m-%d_%H%M%S`
          git tag -a "$timestamp" -m "Push to production"
          git push --tags
